### ISSUE TITLE
Server cannot start when JIDO_API_PORT env var is set

### ISSUE THREAD

**Issue by patrixl** [unscramble/jidoteki-admin-api#12]
When JIDO_API_PORT environment variable is set, the http server cannot start:

> $ JIDO_API_PORT=8888 ./run.l
> HTTP listening on port: 8888
> [app.l:26] !? (port *Port)
> "8888" -- Bad argument

This happens because *JIDO_API_PORT is a string rather than a number, when the environment variable is loaded.

**Comment by aw** [comment]
:open_mouth: I have no idea how this went over me... good catch!

**Comment by aw** [comment]
Fixed and rebased with my regression tests. Thanks for the bug report!
